import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from './providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GPT-Genius",
  description: "Generated by create next app",
};

const RootLayout = ({ children })=> {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      < html lang="en">
          <body className={inter.className}>
            <Providers>
                 {children}
            </Providers>
          </body>
      </html>
    </ClerkProvider>
  );
}
export default RootLayout;